### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mrrfv** [hinell/options-select-bash#1]
Hi! I'd like to use your script in my project [Open Android Backup](https://github.com/mrrfv/open-android-backup), because Inquirer.sh (a similar script) has proven to be very unstable - however, the lack of a license prevents me from doing that. Here's a fragment from GitHub's [documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

Could you please add an open source license to your repo? Thank you.

**Comment by hinell** [comment]
I give you permission to use it for any non-commercial purposes but you should be aware that this script may also be unstable/unpredictable.

I didn't touch it for several years now and it's not optimized. The api is rather loose. I planned to improve it in future but the Ukranian war has changed my plans.

I also suggest you to consider alternatives like [whiptail](https://en.wikibooks.org/wiki/Bash_Shell_Scripting/Whiptail)

Best.

**Comment by hinell** [comment]
I give you permission to use it for any non-commercial purposes but you should be aware that this script may also be unstable/unpredictable.

I didn't touch it for several years now and it's not optimized. The api is rather loose. I planned to improve it in the future but the Ukranian war has changed my plans.

I also suggest you to consider alternatives like [whiptail](https://en.wikibooks.org/wiki/Bash_Shell_Scripting/Whiptail)

Best.
