### ISSUE TITLE
avoid clearing screen before and after selection

### ISSUE THREAD

**Issue by eadmaster** [hinell/options-select-bash#2]
like this:
![alt](https://raw.githubusercontent.com/enquirer/enquirer/master/media/select-prompt.gif)

I've found commenting [this line](https://github.com/hinell/options-select-bash/blob/main/options.select.bash#L177) will get rid of the initial clearing.

**Comment by eadmaster** [comment]
Nevermind, i've switched to:
`echo -e 'opt1\nopt2\nopt3' | fzf --height=~10`

**Comment by hinell** [comment]
This project is a small attempt to replicate what dialog/whiptail can do in bash. Don't expect much. :smile:
